[tool]
id = "com.thelightphone.tool.tesla"
label = "Tesla"
versionCode = 1
versionName = "0.1.0"
permissions = ["android.permission.INTERNET", "android.permission.CAMERA"]
# Use emulator package for development; change to "com.lightos" for real LP3
# Change to "com.thelightphone.sdk.emulator" for emulator development
serverPackage = "com.lightos"
